name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "Thanks for reporting a bug! Please fill out the details below."
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug. What did you expect vs what actually happened?
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Minimal reproduction
      description: Paste the shortest config/steps that reproduce the issue
      render: yaml
    validations:
      required: true
  - type: textarea
    id: error
    attributes:
      label: Error message or unexpected output
      render: text
  - type: dropdown
    id: client
    attributes:
      label: MCP client
      options:
        - Claude Desktop
        - Cursor
        - Windsurf
        - Other
  - type: input
    id: version
    attributes:
      label: commune-mcp version
      placeholder: "e.g. 0.2.1"
    validations:
      required: true
